update travis build config

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,5 +1,33 @@
-#!/usr/bin/env bash
-set -e # halt script on error
+#!/bin/bash
 
+# skip if build is triggered by pull request
+if [ $TRAVIS_PULL_REQUEST == "true" ]; then
+  echo "this is PR, exiting"
+  exit 0
+fi
+
+# enable error reporting to the console
+set -e
+
+# cleanup "_site"
+rm -rf _site
+mkdir _site
+
+# clone remote repo to "_site"
+git clone https://${GITHUB_TOKEN}@github.com/VietAnh1508/a-block-of-code.git --branch gh-pages _site
+
+# gulp
+npm install
+npm install -g gulp gulp-cli
+gulp build
+
+# build with Jekyll into "_site"
 bundle exec jekyll build
-touch ./_site/.nojekyll # this file tells gh-pages that there is no need to build
+
+# push
+cd _site
+git config user.email "vietanhtong1508@gmail.com"
+git config user.name "Viet Anh Tong"
+git add --all
+git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
+git push --force origin gh-pages
